backend/djangoreactapi/djangoreactapi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls')),
]

backend/djangoreactapi/post/urls.py
## 경로 설정해주는 파일
from django.urls import path # path 함수를 이용하기 위해서 선언
from . import views     # from 옆에 .(점)은 현재 폴더(app)를 의미, 현재 폴더에 views.py 가져옴

app_name='post'
urlpatterns = [ 
path('', views.mainpage),
path('resultpage/', views.get_post, name='resultpage'),
  ]
# post -> parameter 로 전송하는거 
# main -> resultpage

backend/djangoreactapi/post/models.py
from django.db import models

backend/djangoreactapi/post/views.py
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import io
import urllib, base64
from urllib.parse import urlparse
import re 
import pandas as pd
import seaborn as sns



# Create your views here.
def mainpage(request):
    return render(request, 'index.html')
"""

def resultpage(request):
    return render(request, 'resultpage.html')
"""
def get_post(request): 
    if request.method == 'GET': 
        urltext = request.GET['urltext'] 
        link1=requests.get(urltext)
        mlist=BeautifulSoup(link1.content,"html.parser") # html.content를 가져오기 
        cont = mlist.find("div",{"class":"jumbotron"}) # 원하는 태그를 선택 (개발자 도구 참조 )
        book=cont.text 
        data = { 'book': book } 
        return render(request, 'resultpage.html', data)
    elif request.method == 'POST':
        urltext = request.POST['urltext'] 
        # 크롤링 해오기 (링크)
        link1=requests.get(urltext)
        mlist=BeautifulSoup(link1.content,"html.parser") # html.content를 가져오기 
        cont = mlist.find("div",{"class":"jumbotron"}) # 원하는 태그를 선택 (개발자 도구 참조 )
        book=cont.text 
        wordimage = word_cloud(book)
        bcnt,blev,bage=basicinfo(book)
        uni=unigram(book)

        data = { 'wordimage': wordimage ,'bcnt':bcnt, 'uni': uni,'blev':blev,'bage':bage} 
        return render(request, 'resultpage.html', data)


def word_cloud(book):
    # wordcloud추출

    spwords=set(STOPWORDS) # 제외할 단어
    wc = WordCloud(stopwords=spwords,background_color="white", contour_width=2,width=1300, colormap='Set2', height=800,max_words=30, max_font_size=170,random_state=42)
    wc.generate(book)
    plt.imshow(wc, interpolation="bilinear")        
    plt.axis('off')
    fig=plt.gcf()
    image = io.BytesIO()
    plt.savefig(image, format='jpeg')
    image.seek(0)  # rewind the data
    string = base64.b64encode(image.read())

    image_64 = 'data:image/png;base64,' + urllib.parse.quote(string)
    #rimage = rescale(image_64, 700)
    return image_64


def basicinfo(book):
    # book의 문장 길이 
    bookcnt = book.split('.')
    cnt=len(bookcnt)
    score=-2.36730268
    lev=0
    age=""

    # level 계산 
    if 0<score<=1:
        lev=1
        age="8세 ~ 9세"
    elif -1<score<=0:
        lev=2
        age="10세 ~ 11세"
    elif -2<score<=-1:
        lev=3
        age="12세 ~ 13세"
    elif -3<score<=-2:
        lev=4
        age="14세 ~ 15세"
    else:
        lev=5
        age="16세 ~ 17세"

    return cnt,lev,age

def unigram(book):
    import string
    book_pred = pd.DataFrame()
    book_pred['word_clean'] = ""
    #filtering the unwanted symbols, spaces, ....etc
    to_replace_by_space = re.compile('[/(){}\[\]|@,;]')
    punctuation = re.compile(f'([{string.punctuation}“”¨«»®´·º½¾¿¡§£₤‘’])')
    bad_symbols = re.compile('[^0-9a-z #+_]')
    spwords=set(STOPWORDS) 


    book = book.lower() # lowercase text
    book = re.sub(punctuation, '',book)
    book = re.sub(to_replace_by_space, " ", book) # replace REPLACE_BY_SPACE_RE symbols by space in text
    book = re.sub(bad_symbols, "", book)         # delete symbols which are in BAD_SYMBOLS_RE from text
    book = " ".join([word for word in book.split(" ") if word not in spwords]) # delete stopwords from text
    book = re.sub(' +', ' ', book)

    
    book_clean=book.split()
    book_pred['word_clean'] =book_clean
    word_counter = book_pred['word_clean'].value_counts().rename_axis('word').reset_index(name='counts')

    plt.figure(figsize=(16, 8))
    ax = sns.barplot(x='counts', y='word', data=word_counter.loc[:20],linewidth=3)
    plt.title("Top 20 words", fontsize=22)
    plt.xlabel("Frequency", fontsize=16)
    plt.yticks(fontsize=13)
    plt.xticks(rotation=45, fontsize=13)
    plt.ylabel("")

    fig=plt.gcf()
    image = io.BytesIO()
    plt.savefig(image, format='jpeg')
    image.seek(0)  # rewind the data
    string = base64.b64encode(image.read())

    image_64 = 'data:image/png;base64,' + urllib.parse.quote(string)
    #rimage = rescale(image_64, 700)
    return image_64

backend/djangoreactapi/post/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Let's Identify It!</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'post/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'post/css/styles.css' %}" rel="stylesheet" />
        <script>
            function send(){
                alert("Complete!");
                document.getElementById("contents").submit();
            }
        </script>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">BigI</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="{% static 'post/assets/img/avataaars.svg' %}" alt="..." />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Let's Identify It!</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <!--p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p>-->
                <form id="contents" name="contents" method="post" action="{% url 'post:resultpage' %}">
                    {% csrf_token %}
                    <div class="form-group">
                      <input name='urltext' type="text" class="form-control"  placeholder="Give Link">
                      <button type="button" class="btn btn-primary mb-2 btn btn-default btn-lg" onclick="send();">Submit</button>
                    </div>
                    
                  </form>
            </div>
        </header>

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            빅데이터 분석반
                            <br />
                            A조
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">About Us</h4>
                        <p class="lead mb-0">
                            김예진   최윤석   정소영
                            <br />
                            이유림   조민경
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Your Website 2021</small></div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

backend/djangoreactapi/post/templates/resultpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Let's Identify It!</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'post/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'post/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <div id="wrapper">

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">
    
                <!-- Main Content -->
                
                    <!-- Topbar -->
                    <nav class="navbar navbar-expand-lg bg-secondary fixed-top" id="mainNav">
                        <div class="container">
                            <a class="navbar-brand" href="#page-top">BigI</a>
                        </div>
                    </nav>
                    <header class="masthead bg-white text-green-600 text-center">
                    <!-- End of Topbar -->
    
                    <!-- Begin Page Content -->
                    <div class="container-fluid">
    
                        <!-- Page Heading -->
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h1 mb-0 text-purple-600">Dashboard</h1>
                            <a href="#" class="d-none d-sm-inline-block btn btn btn-primary shadow-sm"><i
                                    class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
                        </div>
    
                        <!-- Content Row -->
                        <div class="row">
    
                            <!-- Earnings (Monthly) Card Example -->
                            <div class="col-6 col-md-4 mb-4 ">
                                <div class="card border-left-primary mb-3 shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-1">
                                                <div class="h5 mb-3 font-weight-bold text-primary text-uppercase">
                                                    책 난이도 </div>
                                                <div class="h2 font-weight-bold text-gray-800">lv {{blev}}</div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <!-- Earnings (Monthly) Card Example -->
                            <div class="col-6 col-md-4 mb-4">
                                <div class="card border-left-success shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="h5 mb-3 text-xs font-weight-bold text-primary text-uppercase ">
                                                    책 길이</div>
                                                <div class="h2 font-weight-bold text-gray-800">{{bcnt}}</div>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>
                            
                            <div class="col-6 col-md-4 mb-4">
                                <div class="card border-left-success shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="h5 mb-3 text-xs font-weight-bold text-primary text-uppercase">
                                                    추천 나이</div>
                                                <div class="h2 font-weight-bold text-gray-800">{{bage}}</div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                        <!-- Content Row -->
    
                        <div class="row">
    
                            <!-- Area Chart -->
                            <div class="col-12 col-xl-8">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header bg-primary py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h4 class="m-2 font-weight-bold text-white">Unigram</h4>
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                            <img class="card-img-top flex-row" src="{{uni}}"><br/>
                                       
                                    </div>
                                </div>
                            </div>
    
                            <!-- Pie Chart -->
                            <div class="col-12 col-xl-4">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header bg-primary py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h4 class="m-2 font-weight-bold text-white">WordCloud</h4>
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                        
                                            <!--canvas id="myPieChart"></canvas-->
                                            <img class="card-img-top flex-row" src="{{ wordimage }}"><br/>
                        
                                    </div>
                                </div>
                            </div>
                        </div>
    
    
                    </div>
                    <!-- /.container-fluid -->
    
                </header>
                <!-- End of Main Content -->

                <!-- End of Footer -->
    
            </div>
            <!-- End of Content Wrapper -->
    
        </div>
        
     
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>



</html>